version: "3.8"

services:
  backend:
    image: josebenites21/planilla-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:c1ba2a6f892999c28679f7f3d5c75c@mongodb:27017/planilla?authSource=admin
    networks:
      - backend-planilla-network
      - general_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: josebenites21/new_frontend:latest
    ports:
      - "4200:80"
    networks:
      - backend-planilla-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  backend-planilla-network:
    external: true
  general_network:
    external: true