version: "3.8"

services:
  backend:
    image: josebenites211/planilla-backend:latest
    ports:
      - "8888:3000"  # Puerto 8888 externo, 3000 interno
    environment:
      - MONGO_URI=mongodb://admin:c1ba2a6f892999c28679f7f3d5c75c@mongodb:27017/planilla?authSource=admin
    networks:
      - backend-planilla-network
      - general_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.include-stopped=true"

  frontend:
    image: josebenites211/new_frontend:latest
    ports:
      - "9999:80"  # Puerto 9999 externo, 80 interno
    networks:
      - backend-planilla-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.include-stopped=true"

  # WATCHTOWER - Actualización automática
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command: --debug --include-stopped --revive-stopped --cleanup --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - general_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true

networks:
  backend-planilla-network:
    external: true
  general_network:
    external: true
